package com.ilikeclouds.pricepredictorplugin;

import java.util.List;

/** Mirrors docs/index.json generated by commit_output.py. */
public class IndexData
{
    public String          generated_at;
    public int             item_count;
    public List<IndexItem> items;

    public static class IndexItem
    {
        public int    id;
        public String name;
        public int    current_price;
        public String model_tier;
        public String generated_at;
    }
}
